apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-arm64
  labels:
    app: nginx-arm64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-arm64
  template:
    metadata:
      labels:
        app: nginx-arm64
    spec:
      containers:
      - image: arm64v8/nginx
        name: nginx
        ports:
        - containerPort: 80